### ISSUE TITLE
MySQL error on upgrade from 1.0.5 to 1.0.6

### ISSUE THREAD

**Issue by MixasikM** [SaifurRahmanMohsin/oc-rest-plugin#16]
Update failed
"SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'extras' can't have a default value (SQL: alter table `mohsin_rest_nodes` add `extras` json not null default '{}' after `is_disabled`)" on line 664 of /***/vendor/laravel/framework/src/Illuminate/Database/Connection.php

mysql-server-5.7
php7.2
Ubuntu 18.04

**Comment by SaifurRahmanMohsin** [comment]
There, it should be fixed now. Try reinstalling the plugin. If the issue persists or you face any other bugs, feel free to open an issue here.
